# Generated by Django 5.1.7 on 2025-04-21 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('company_code', models.CharField(max_length=50, unique=True, verbose_name='المعرف الداخلي')),
                ('contact_name', models.CharField(max_length=100, verbose_name='اسم المسؤول')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم جوال المسؤول')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف الشركة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('field', models.CharField(max_length=100, verbose_name='مجال العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الوظيفي')),
                ('user_type', models.CharField(choices=[('internal_admin', 'مسؤول داخلي'), ('internal_employee', 'موظف داخلي'), ('client_admin', 'مدير شركة عميلة'), ('client_employee', 'موظف شركة عميلة')], default='client_employee', max_length=20, verbose_name='نوع المستخدم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='الصورة الشخصية')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='الشركة التابع لها')),
            ],
            options={
                'verbose_name': 'المستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
    ]
