# Generated by Django 5.1.7 on 2025-04-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_company', models.CharField(choices=[('employee', 'موظف'), ('supervisor', 'مشرف'), ('admin', 'مدير الشركة')], default='employee', max_length=20, verbose_name='الدور داخل الشركة')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name='هل هو مدير الشركة؟')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف شركة عميلة',
                'verbose_name_plural': 'موظفو الشركات',
            },
        ),
        migrations.CreateModel(
            name='InternalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مسؤول نظام'), ('support', 'دعم فني'), ('sales', 'مندوب مبيعات'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الدور')),
                ('domain_verified', models.BooleanField(default=False, verbose_name='تم التحقق من الدومين')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف داخلي',
                'verbose_name_plural': 'الموظفون الداخليون',
            },
        ),
    ]
