# Generated by Django 5.1.7 on 2025-04-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientuser_internalemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('max_employees', models.PositiveIntegerField(verbose_name='الحد الأقصى للموظفين')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('features', models.TextField(blank=True, null=True, verbose_name='المزايا')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptionplan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'اشتراك شركة',
                'verbose_name_plural': 'اشتراكات الشركات',
            },
        ),
    ]
