# Generated by Django 5.1.7 on 2025-04-21 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriptionplan_companysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 21, 18, 43, 27, 144040, tzinfo=datetime.timezone.utc), verbose_name='تاريخ الإضافة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuser',
            name='employees_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الموظفين'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
    ]
