# Generated by Django 5.1.7 on 2025-05-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clientuser_created_at_clientuser_employees_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
