# Generated by Django 5.1.7 on 2025-04-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_clientuser_created_at_clientuser_employees_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expiring', 'ينتهي قريباً'), ('expired', 'منتهي')], default='active', max_length=20, verbose_name='الحالة')),
                ('terms', models.TextField(verbose_name='الشروط')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'عقد شركة',
                'verbose_name_plural': 'عقود الشركات',
            },
        ),
    ]
