# Generated by Django 5.1.7 on 2025-05-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_companycontract_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='last_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد الأخير'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات التجديد'),
        ),
    ]
