# Generated by Django 5.1.7 on 2025-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_companycontract_last_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='renewed_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التجديد'),
        ),
    ]
