# Generated by Django 5.1.7 on 2025-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_companycontract_renewed_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='تجديد تلقائي'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='contract_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة العقد'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='next_renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التجديد القادم'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'تحويل بنكي'), ('credit_card', 'بطاقة ائتمان'), ('e_payment', 'دفع إلكتروني')], max_length=20, null=True, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع'), ('pending', 'قيد الانتظار')], max_length=20, null=True, verbose_name='حالة الدفع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='website_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للموقع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='website_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموقع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='website_schedule_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم جدول الموقع'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expiring', 'ينتهي قريباً'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='حالة العقد'),
        ),
    ]
