# Generated by Django 5.1.7 on 2025-05-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_companycontract_auto_renewal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontract',
            name='website_email',
        ),
        migrations.RemoveField(
            model_name='companycontract',
            name='website_name',
        ),
        migrations.RemoveField(
            model_name='companycontract',
            name='website_schedule_number',
        ),
        migrations.AddField(
            model_name='companycontract',
            name='signer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للموقّع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='signer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الموقّع'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='signer_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الصفة الوظيفية للموقّع'),
        ),
    ]
