# Generated by Django 5.1.7 on 2025-05-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_companycontract_website_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('max_employees', models.PositiveIntegerField(verbose_name='الحد الأقصى للموظفين')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('features', models.TextField(blank=True, null=True, verbose_name='المزايا')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'باقة اشتراك',
                'verbose_name_plural': 'باقات الاشتراك',
            },
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='تجديد تلقائي؟'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='قيمة الخصم (نسبة %)'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع'), ('pending', 'قيد الانتظار')], default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('expiring', 'ينتهي قريباً'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.subscriptionplan', verbose_name='الباقة'),
        ),
    ]
