# Generated by Django 5.1.7 on 2025-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_subscriptionplan_alter_companycontract_auto_renewal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإجمالي بعد الخصم'),
        ),
    ]
