# Generated by Django 5.1.7 on 2025-05-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_companycontract_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تمت الموافقة بواسطة'),
        ),
        migrations.CreateModel(
            name='ContractRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التجديد')),
                ('old_end_date', models.DateField(verbose_name='تاريخ النهاية السابق')),
                ('new_end_date', models.DateField(verbose_name='تاريخ النهاية الجديد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('updated_by', models.CharField(max_length=255, verbose_name='تم التجديد بواسطة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.companycontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'تجديد عقد',
                'verbose_name_plural': 'سجل تجديدات العقود',
            },
        ),
    ]
