# Generated by Django 5.1.7 on 2025-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_companycontract_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='companycontract',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الموظفين'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='final_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الإجمالي شامل الضريبة'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='companycontract',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة (%)'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_per_employee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='السعر لكل موظف (شهريًا)'),
            preserve_default=False,
        ),
    ]
