# Generated by Django 5.1.7 on 2025-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_remove_subscriptionplan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='تم الإلغاء؟'),
        ),
    ]
