# Generated by Django 5.1.7 on 2025-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('company_name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('employees_count', models.PositiveIntegerField(verbose_name='عدد الموظفين')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('request_type', models.CharField(choices=[('trial', 'طلب عرض تجريبي'), ('pricing', 'طلب عرض سعر')], max_length=10, verbose_name='نوع الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('rejection_note', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('quote_link', models.URLField(blank=True, null=True, verbose_name='رابط عرض السعر')),
            ],
            options={
                'verbose_name': 'طلب اشتراك',
                'verbose_name_plural': 'الطلبات',
            },
        ),
    ]
