# Generated by Django 5.1.7 on 2025-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('employees_count', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('request_type', models.CharField(choices=[('trial', 'عرض تجريبي'), ('pricing', 'عرض سعر')], max_length=10)),
                ('status', models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد المراجعة', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('quote_link', models.URLField(blank=True, null=True, verbose_name='رابط عرض السعر')),
            ],
        ),
    ]
